### ISSUE TITLE
移动端视频播放相关问题

### ISSUE THREAD

**Issue by forever-z-133** [foreverZ133/blogs#34]
### HTML5 默认情况

在 PC 上，video 标签是有默认封面图 poster 的，播放暂停也没啥毛病。

![PC上播放视频的样子](https://user-images.githubusercontent.com/22021589/42805451-6c006752-89de-11e8-8ce4-93f5756e7d10.jpg)

但移动端没有封面图，播放时会自动全屏(非所有手机)，退出全屏会存在封面图但却是铺满 video 的。

![手机上播放视频的样子](https://user-images.githubusercontent.com/22021589/42811302-ccee61b4-89ec-11e8-8ba3-81962c53e0a4.png)

所以本文主要探讨就是这个了，如何让移动端的视频有封面图，并顺带解决一些移动端视频播放的问题。

### 使用 canvas 绘制

PC 上，可以用 canvas 来画视频，注意需要 loadeddata 事件之后。
```js
$video.addEventListener('loadeddata', () => {
  createVideoPoster(this)
});
function createVideoPoster($video) {
  var oldCanvas = $video.parentNode.appendChild(canvas);
  oldCanvas && oldCanvas.remove();
  $video.setAttribute('crossOrigin', 'Anonymous');
  var canvas = document.createElement('canvas');
  var winW = canvas.width = $video.parentNode.offsetWidth;
  var winH = canvas.height = $video.parentNode.offsetHeight;
  var w = $video.clientWidth;
  var h = $video.clientHeight;
  if (winW / winH > w / h) {
    hh = winH; ww = w / h * winH;
  } else {
    ww = winW; hh = h / w * winW;
  }
  canvas.getContext('2d').drawImage($video, winW/2-ww/2, winH/2-hh/2, ww, hh);
  $video.parentNode.appendChild(canvas);
}
```

crossOrigin 效果并不绝对正确，如果出现也没法 catch 到，感觉只能初始前弄个默认图。
跨域还会无法使用 canvas.toDataUrl，当然也可以不转图片咯，看需求吧。

这里 $video.setAttribute('crossOrigin', 'Anonymous') 有点迷，大小写都可以，
$video.crossorigin = 'anonymous' 必须小写。

然而较多移动端上依旧是无效的，无论延时多久都没用，就跟 autoplay 那样你体会一下。
获取视频时间的 video.duration 也是同理，移动端浏览器对这类限制真是强硬。

### 后端帮忙截屏

用 poster 属性搞张默认图呀，当然是可以的。因为这个锅直接就甩给后端/原生开发咯。
在视频保存前或显示前，把视频地址发给后端，后端帮我截屏返回图片地址。
看搜到的资料，是 streamReader 还是 ffmpeg 应该都不难。

这时候只管嘤嘤嘤感觉是没错的，但还是有不美好的地方。
因为播放后暂停，poster 就不显示了，暂停画面又变成铺满 video 了。

### 阿里云视频截图服务

[文档](https://help.aliyun.com/document_detail/64555.html?spm=a2c4g.11186623.6.1031.BuoKRf) / [DEMO](https://oss-uat.xuebangsoft.net/13bef702-20f7-438c-97fb-8bacbaba18eb.mp4?x-oss-process=video/snapshot,t_500)

只需要在视频链接后面加上 `?x-oss-process=video/snapshot,t_500` 即可。
还可以加上 `f_jpg,w_800,h_600,m_fast` 几个参数，除了高清需求好像不咋用不上。
很简单有木有，诚恳地感谢大佬和开源服务。

当然，仅放在阿里云上的资源才享有这样的功能。

但在之后的测试中，仅 mkv/mov/mp4 可以用该方法获取截图，其他会报 not supported format 错误。

还有另一个无关问题，项目中是把视频上传到阿里 OSS，
这个操作后，原本在 PC 上的 avi/mpeg/wmv 莫名不能播放了，移动端没事。

### 解决暂停画面铺满 video

为了解决上面的问题，video 不可避免的要隐藏起来，不然用默认样式产品也不会催了我一周。

用弄好的封面图替代 video 原来的位置，video 隐藏起来，点击图片就 video.play()。

```html
<div class="video-box">
  <video src preload controls></video>
  <div class="poster" style="background-image: url()">
</div>
```
```css
.video-box {
  position: relative;
  overflow: hidden;
}
.video-box:before {
  content: '';
  display: block;
  padding-top: 50.67%;
}
.video-box > video {
  position: fixed;
  z-index: -1;
  top: 0;
  left: -999em;
  object-fit: contain;
  background: rgba(0,0,0,.8);
}
.video-box >  .poster{
  position: absolute;
  top: 0; left: 0;
  right: 0; bottom: 0;
  background-size: contain;
  background-position: center;
  background-repeat: no-repeat;
}
```
```js
var isMobile = window.innerWidth < 768;
$('body').on('click', '.video-box', function () {
  var $video = this.querySelector('video');
  playVideo($video);
});
if (isMobile) {
  $(window).on('hashchange', function() {
    if (!location.hash || location.hash === '#') {
      $('video').each(function(){ stopVideo(this); });
    }
  });
}
function playVideo($video) {
  if (isMobile) {
    location.hash = "videoPlay" + Math.random().toString(16).slice(2,6);
    $($video).off().on('pause', function(){ history.back(); });
  } else {
    $($video).off().on('ended', function(){ stopVideo($video); });
  }
  $video.play();
  $video.style.zIndex = 1;
  $video.style.left = '0';
}
function stopVideo($video) {
  $video.pause();
  $video.currentTime = 0;
  $video.style.zIndex = -1;
  $video.style.left = '-999em';
}
```

注意此处用的偏移式的隐藏方法，因为 display:none 的话 preload 是不起效的。

另外就是如何监听暂停问题，说实话这里我也没找到完全之策，只得用 hash 和 onpause 来了。

### 视频播放完有广告问题

这个问题只需几个属性即可解决，看到 x5-video 前缀你是不是懂了什么。
但加与不加的样式是不同的，这就由产品去判断吧。
`x5-video-player-type="h5" x5-video-player-fullscreen webkit-playsinline playsinline`

另外，加上这个还有个好处，就是元素能覆盖在 video 之上了。

> ### 其他
https://help.aliyun.com/document_detail/66804.html?spm=a2c4g.11186623.6.613.nw5D3m
各家大厂的开放服务随便翻翻感觉都是惊喜呀，比如文件转码、直播、视频上传等等。

起初我以为视频不能播放是因为文件格式问题，但后来测试中还是遇上了播放 MP4 有声音没画面的情况，才算理解为何大多教材只说支持某编码格式而非文件格式。
![视频的编码格式](https://image.ipaiban.com/upload-ueditor-image-20180724-1532397994458059413.png)
